//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestingGroundMVC.AdvWorksManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Employees", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", ItemName="Employee")]
    [System.SerializableAttribute()]
    public class Employees : System.Collections.Generic.List<MyTestingGroundMVC.AdvWorksManagementService.Employee> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", ConfigurationName="AdvWorksManagementService.EmployeeServiceContract")]
    public interface EmployeeServiceContract {
        
        // CODEGEN: Generating message contract since the operation GetEmployees is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetEmployees", ReplyAction="http://MyTestingGroundService.Model/2011/MyTestingGroundService/EmployeeServiceCo" +
            "ntract/GetEmployeesResponse")]
        MyTestingGroundMVC.AdvWorksManagementService.EmployeeResponse GetEmployees(MyTestingGroundMVC.AdvWorksManagementService.GetEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        public GetEmployeesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", Order=0)]
        public MyTestingGroundMVC.AdvWorksManagementService.Employees Employees;
        
        public EmployeeResponse() {
        }
        
        public EmployeeResponse(MyTestingGroundMVC.AdvWorksManagementService.Employees Employees) {
            this.Employees = Employees;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceContractChannel : MyTestingGroundMVC.AdvWorksManagementService.EmployeeServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceContractClient : System.ServiceModel.ClientBase<MyTestingGroundMVC.AdvWorksManagementService.EmployeeServiceContract>, MyTestingGroundMVC.AdvWorksManagementService.EmployeeServiceContract {
        
        public EmployeeServiceContractClient() {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyTestingGroundMVC.AdvWorksManagementService.EmployeeResponse MyTestingGroundMVC.AdvWorksManagementService.EmployeeServiceContract.GetEmployees(MyTestingGroundMVC.AdvWorksManagementService.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public MyTestingGroundMVC.AdvWorksManagementService.Employees GetEmployees() {
            MyTestingGroundMVC.AdvWorksManagementService.GetEmployeesRequest inValue = new MyTestingGroundMVC.AdvWorksManagementService.GetEmployeesRequest();
            MyTestingGroundMVC.AdvWorksManagementService.EmployeeResponse retVal = ((MyTestingGroundMVC.AdvWorksManagementService.EmployeeServiceContract)(this)).GetEmployees(inValue);
            return retVal.Employees;
        }
    }
}
