//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOS.Client.AdvWorksManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Employees", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", ItemName="Employee")]
    [System.SerializableAttribute()]
    public class Employees : System.Collections.Generic.List<SOS.Client.AdvWorksManagementService.Employee> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOS.Client.AdvWorksManagementService.PurchaseOrder[] PurchaseOrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public SOS.Client.AdvWorksManagementService.PurchaseOrder[] PurchaseOrders {
            get {
                return this.PurchaseOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrdersField, value) != true)) {
                    this.PurchaseOrdersField = value;
                    this.RaisePropertyChanged("PurchaseOrders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrder", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PurchaseOrderIDField;
        
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PurchaseOrderID {
            get {
                return this.PurchaseOrderIDField;
            }
            set {
                if ((this.PurchaseOrderIDField.Equals(value) != true)) {
                    this.PurchaseOrderIDField = value;
                    this.RaisePropertyChanged("PurchaseOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((this.ShipDateField.Equals(value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal TaxAmt {
            get {
                return this.TaxAmtField;
            }
            set {
                if ((this.TaxAmtField.Equals(value) != true)) {
                    this.TaxAmtField = value;
                    this.RaisePropertyChanged("TaxAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PurchaseOrderDetails", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", ItemName="PurchaseOrderDetail")]
    [System.SerializableAttribute()]
    public class PurchaseOrderDetails : System.Collections.Generic.List<SOS.Client.AdvWorksManagementService.PurchaseOrderDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetail", Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceivedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderQty {
            get {
                return this.OrderQtyField;
            }
            set {
                if ((this.OrderQtyField.Equals(value) != true)) {
                    this.OrderQtyField = value;
                    this.RaisePropertyChanged("OrderQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal ReceivedQty {
            get {
                return this.ReceivedQtyField;
            }
            set {
                if ((this.ReceivedQtyField.Equals(value) != true)) {
                    this.ReceivedQtyField = value;
                    this.RaisePropertyChanged("ReceivedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", ConfigurationName="AdvWorksManagementService.EmployeeServiceContract")]
    public interface EmployeeServiceContract {
        
        // CODEGEN: Generating message contract since the operation GetEmployees is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetEmployees", ReplyAction="http://MyTestingGroundService.Model/2011/MyTestingGroundService/EmployeeServiceCo" +
            "ntract/GetEmployeesResponse")]
        SOS.Client.AdvWorksManagementService.EmployeeResponse GetEmployees(SOS.Client.AdvWorksManagementService.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetPurchaseOrderDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPurchaseOrderDetails", ReplyAction="http://MyTestingGroundService.Model/2011/MyTestingGroundService/EmployeeServiceCo" +
            "ntract/GetPurchaseOrderDetailsResponse")]
        SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsResponse GetPurchaseOrderDetails(SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        public GetEmployeesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", Order=0)]
        public SOS.Client.AdvWorksManagementService.Employees Employees;
        
        public EmployeeResponse() {
        }
        
        public EmployeeResponse(SOS.Client.AdvWorksManagementService.Employees Employees) {
            this.Employees = Employees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", Order=0)]
        public int PurchaseOrderID;
        
        public PurchaseOrderDetailsRequest() {
        }
        
        public PurchaseOrderDetailsRequest(int PurchaseOrderID) {
            this.PurchaseOrderID = PurchaseOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyTestingGroundService.Model/2011/MyTestingGroundService", Order=0)]
        public SOS.Client.AdvWorksManagementService.PurchaseOrderDetails PurchaseOrderDetails;
        
        public PurchaseOrderDetailsResponse() {
        }
        
        public PurchaseOrderDetailsResponse(SOS.Client.AdvWorksManagementService.PurchaseOrderDetails PurchaseOrderDetails) {
            this.PurchaseOrderDetails = PurchaseOrderDetails;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceContractChannel : SOS.Client.AdvWorksManagementService.EmployeeServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceContractClient : System.ServiceModel.ClientBase<SOS.Client.AdvWorksManagementService.EmployeeServiceContract>, SOS.Client.AdvWorksManagementService.EmployeeServiceContract {
        
        public EmployeeServiceContractClient() {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.Client.AdvWorksManagementService.EmployeeResponse SOS.Client.AdvWorksManagementService.EmployeeServiceContract.GetEmployees(SOS.Client.AdvWorksManagementService.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public SOS.Client.AdvWorksManagementService.Employees GetEmployees() {
            SOS.Client.AdvWorksManagementService.GetEmployeesRequest inValue = new SOS.Client.AdvWorksManagementService.GetEmployeesRequest();
            SOS.Client.AdvWorksManagementService.EmployeeResponse retVal = ((SOS.Client.AdvWorksManagementService.EmployeeServiceContract)(this)).GetEmployees(inValue);
            return retVal.Employees;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsResponse SOS.Client.AdvWorksManagementService.EmployeeServiceContract.GetPurchaseOrderDetails(SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsRequest request) {
            return base.Channel.GetPurchaseOrderDetails(request);
        }
        
        public SOS.Client.AdvWorksManagementService.PurchaseOrderDetails GetPurchaseOrderDetails(int PurchaseOrderID) {
            SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsRequest inValue = new SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsRequest();
            inValue.PurchaseOrderID = PurchaseOrderID;
            SOS.Client.AdvWorksManagementService.PurchaseOrderDetailsResponse retVal = ((SOS.Client.AdvWorksManagementService.EmployeeServiceContract)(this)).GetPurchaseOrderDetails(inValue);
            return retVal.PurchaseOrderDetails;
        }
    }
}
