//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace SOS.DataContracts
{
	/// <summary>
	/// Data Contract Class - Employee
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService", Name = "Employee")]
	public partial class Employee 
	{
		private int id;
		private string title;
		private string gender;
		private System.Collections.Generic.List<PurchaseOrder> purchaseOrders;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public int Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Title", IsRequired = false, Order = 1)]
		public string Title
		{
		  get { return title; }
		  set { title = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Gender", IsRequired = false, Order = 2)]
		public string Gender
		{
		  get { return gender; }
		  set { gender = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PurchaseOrders", IsRequired = false, Order = 3)]
		public System.Collections.Generic.List<PurchaseOrder> PurchaseOrders
		{
		  get { return purchaseOrders; }
		  set { purchaseOrders = value; }
		}				
	}
}

