//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace SOS.DataContracts
{
	/// <summary>
	/// Data Contract Class - Product
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService", Name = "Product")]
	public partial class Product 
	{
		private int productID;
		private string name;
		private string productNumber;
		private string color;
		private int reorderPoint;
		private double standardCost;
		private double listPrice;
		private decimal weight;
		private System.DateTime sellStartDate;
		private System.DateTime sellEndDate;
		private System.DateTime discontinuedDate;
		private ProductCostHistories productCostHistories;
		
		[WcfSerialization::DataMember(Name = "ProductID", IsRequired = false, Order = 0)]
		public int ProductID
		{
		  get { return productID; }
		  set { productID = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 1)]
		public string Name
		{
		  get { return name; }
		  set { name = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProductNumber", IsRequired = false, Order = 2)]
		public string ProductNumber
		{
		  get { return productNumber; }
		  set { productNumber = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Color", IsRequired = false, Order = 3)]
		public string Color
		{
		  get { return color; }
		  set { color = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReorderPoint", IsRequired = false, Order = 4)]
		public int ReorderPoint
		{
		  get { return reorderPoint; }
		  set { reorderPoint = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "StandardCost", IsRequired = false, Order = 5)]
		public double StandardCost
		{
		  get { return standardCost; }
		  set { standardCost = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListPrice", IsRequired = false, Order = 6)]
		public double ListPrice
		{
		  get { return listPrice; }
		  set { listPrice = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Weight", IsRequired = false, Order = 7)]
		public decimal Weight
		{
		  get { return weight; }
		  set { weight = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SellStartDate", IsRequired = false, Order = 8)]
		public System.DateTime SellStartDate
		{
		  get { return sellStartDate; }
		  set { sellStartDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SellEndDate", IsRequired = false, Order = 9)]
		public System.DateTime SellEndDate
		{
		  get { return sellEndDate; }
		  set { sellEndDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DiscontinuedDate", IsRequired = false, Order = 10)]
		public System.DateTime DiscontinuedDate
		{
		  get { return discontinuedDate; }
		  set { discontinuedDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProductCostHistories", IsRequired = false, Order = 11)]
		public ProductCostHistories ProductCostHistories
		{
		  get { return productCostHistories; }
		  set { productCostHistories = value; }
		}				
	}
}

