//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace SOS.DataContracts
{
	/// <summary>
	/// Data Contract Class - PurchaseOrder
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService", Name = "PurchaseOrder")]
	public partial class PurchaseOrder 
	{
		private int purchaseOrderID;
		private System.DateTime orderDate;
		private System.DateTime shipDate;
		private decimal taxAmt;
		private decimal subTotal;
		
		[WcfSerialization::DataMember(Name = "PurchaseOrderID", IsRequired = true, Order = 0)]
		public int PurchaseOrderID
		{
		  get { return purchaseOrderID; }
		  set { purchaseOrderID = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "OrderDate", IsRequired = true, Order = 1)]
		public System.DateTime OrderDate
		{
		  get { return orderDate; }
		  set { orderDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ShipDate", IsRequired = false, Order = 2)]
		public System.DateTime ShipDate
		{
		  get { return shipDate; }
		  set { shipDate = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TaxAmt", IsRequired = false, Order = 3)]
		public decimal TaxAmt
		{
		  get { return taxAmt; }
		  set { taxAmt = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SubTotal", IsRequired = false, Order = 4)]
		public decimal SubTotal
		{
		  get { return subTotal; }
		  set { subTotal = value; }
		}				
	}
}

