//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace SOS.DataContracts
{
	/// <summary>
	/// Data Contract Class - PurchaseOrderDetails
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService")]
	public partial class PurchaseOrderDetails : System.Collections.Generic.List<PurchaseOrderDetail>
	{
	}
}

