
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace SOS.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PurchaseOrderDetailsResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class PurchaseOrderDetailsResponse
	{
		private SOS.DataContracts.PurchaseOrderDetails purchaseOrderDetails;
	 		
		[WCF::MessageBodyMember(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService", Name = "PurchaseOrderDetails")]
		public SOS.DataContracts.PurchaseOrderDetails PurchaseOrderDetails
		{
			get { return purchaseOrderDetails; }
			set { purchaseOrderDetails = value; }
		}
	}
}

