
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace SOS.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PurchaseOrderDetailsRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class PurchaseOrderDetailsRequest
	{
		private int purchaseOrderID;
	 		
		[WCF::MessageBodyMember(Namespace = "http://MyTestingGroundService.Model/2011/MyTestingGroundService", Name = "PurchaseOrderID")]
		public int PurchaseOrderID
		{
			get { return purchaseOrderID; }
			set { purchaseOrderID = value; }
		}
	}
}

